//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORViewEmployeeData
    {
        public long ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<double> Salary { get; set; }
        public bool IsDeleted { get; set; }
        public string Designation { get; set; }
        public Nullable<long> CompanyId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
