//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PMProjectResource
    {
        public long Id { get; set; }
        public Nullable<int> WorkerId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> RoleId { get; set; }
        public Nullable<int> PercentageEstimation { get; set; }
        public Nullable<int> MilestoneId { get; set; }
        public Nullable<int> GivenPercentage { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
