//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PMProjectRole
    {
        public long Id { get; set; }
        public string Title { get; set; }
        public string Details { get; set; }
        public Nullable<int> GeneralPercentage { get; set; }
        public Nullable<int> OPercentage { get; set; }
        public string Variations { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public string MandatoryChecks { get; set; }
        public string RolesInvolves { get; set; }
        public Nullable<long> CompanyId { get; set; }
    }
}
