//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PMProjectMSTask
    {
        public long Id { get; set; }
        public Nullable<long> ProjectId { get; set; }
        public Nullable<long> MilestoneId { get; set; }
        public string Title { get; set; }
        public string Details { get; set; }
        public Nullable<System.DateTime> BetaDate { get; set; }
        public Nullable<System.DateTime> AlphaDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public string TaskType { get; set; }
        public Nullable<long> AlphaTime { get; set; }
        public Nullable<long> BetaTime { get; set; }
        public string TaskStatus { get; set; }
        public Nullable<System.DateTime> ActualAlphaDate { get; set; }
        public Nullable<System.DateTime> ActualBetaDate { get; set; }
        public Nullable<long> ActualAlphaTime { get; set; }
        public Nullable<long> ActualBetaTime { get; set; }
        public string TimeDifferReason { get; set; }
        public Nullable<long> AssignedUserId { get; set; }
        public Nullable<long> CompanyId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<long> WorkedInIMinutes { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
