//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PMProjectWorker
    {
        public long Id { get; set; }
        public string Title { get; set; }
        public Nullable<bool> ProjectBased { get; set; }
        public Nullable<decimal> Reserves { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public Nullable<long> SeatCharge { get; set; }
        public Nullable<long> HourlyRate { get; set; }
        public string Password { get; set; }
        public string Phone { get; set; }
        public string Skype { get; set; }
        public Nullable<long> ResourceType { get; set; }
        public string Email { get; set; }
        public Nullable<long> CompanyId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
