//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMonthlyHR
    {
        public long ID { get; set; }
        public string Description { get; set; }
        public Nullable<double> Tax { get; set; }
        public Nullable<double> EOB { get; set; }
        public Nullable<double> Misc { get; set; }
        public Nullable<long> EmployeeId { get; set; }
        public string LecturePerDay { get; set; }
        public Nullable<double> Advance { get; set; }
        public Nullable<bool> C1st { get; set; }
        public Nullable<bool> C2nd { get; set; }
        public Nullable<bool> C3rd { get; set; }
        public Nullable<bool> C4th { get; set; }
        public Nullable<bool> C5th { get; set; }
        public Nullable<bool> C6th { get; set; }
        public Nullable<bool> C7th { get; set; }
        public Nullable<bool> C8th { get; set; }
        public Nullable<bool> C9th { get; set; }
        public Nullable<bool> C10th { get; set; }
        public Nullable<bool> C11th { get; set; }
        public Nullable<bool> C12th { get; set; }
        public Nullable<bool> C13th { get; set; }
        public Nullable<bool> C14th { get; set; }
        public Nullable<bool> C15th { get; set; }
        public Nullable<bool> C16th { get; set; }
        public Nullable<bool> C17th { get; set; }
        public Nullable<bool> C18th { get; set; }
        public Nullable<bool> C19th { get; set; }
        public Nullable<bool> C20th { get; set; }
        public Nullable<bool> C21th { get; set; }
        public Nullable<bool> C22th { get; set; }
        public Nullable<bool> C23th { get; set; }
        public Nullable<bool> C24th { get; set; }
        public Nullable<bool> C25th { get; set; }
        public Nullable<bool> C26th { get; set; }
        public Nullable<bool> C27th { get; set; }
        public Nullable<bool> C28th { get; set; }
        public Nullable<bool> C29th { get; set; }
        public Nullable<bool> C30th { get; set; }
        public Nullable<bool> C31th { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<long> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string Yearr { get; set; }
        public string Monthh { get; set; }
    }
}
